import { BesserProject } from '../../components/modals/create-project-modal/CreateProjectModal';
import { Diagram } from '../diagram/diagramSlice';

// Dynamic imports for JSZip and file-saver
async function loadDependencies() {
  const JSZip = (await import('jszip')).default;
  const { saveAs } = await import('file-saver');
  return { JSZip, saveAs };
}

// Simple download helper
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Export project as a single JSON file (temporary solution)
export async function exportProjectAsJson(project: BesserProject, diagrams: Diagram[]) {
  const exportData = {
    project,
    diagrams,
    exportedAt: new Date().toISOString(),
    version: '1.0.0'
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { 
    type: 'application/json' 
  });
  
  const filename = `${project.name.replace(/[^a-z0-9]/gi, '_') || 'project'}.json`;
  downloadBlob(blob, filename);
}

// ZIP export (now that JSZip and file-saver are installed)
export async function useExportProjectJSON(project: BesserProject, diagrams: Diagram[]) {
  try {
    const JSZip = (await import('jszip')).default;

    const zip = new JSZip();

    // Add project metadata
    zip.file('project.json', JSON.stringify(project, null, 2));

    // Add each diagram as a separate JSON file
    const diagramsFolder = zip.folder('diagrams');
    if (diagramsFolder) {
      diagrams.forEach(diagram => {
        const filename = `${(diagram.title || diagram.id).replace(/[^a-z0-9]/gi, '_').toLowerCase()}.json`;
        diagramsFolder.file(filename, JSON.stringify(diagram, null, 2));
      });
    }

    // Add README with project information
    const readme = `# ${project.name}

${project.description || 'No description provided.'}

## Project Information
- **Owner:** ${project.owner || 'Unknown'}
- **Created:** ${new Date(project.createdAt).toLocaleDateString()}
- **Diagrams:** ${diagrams.length}

## Export Information
- **Exported:** ${new Date().toLocaleDateString()}
- **Version:** 1.0.0

## Contents
- \`project.json\` - Project metadata and settings
- \`diagrams/\` - Individual diagram files in JSON format
- \`README.md\` - This file

## How to Import
1. Open BESSER Web Modeling Editor
2. Go to File > Import Project
3. Select this ZIP file
4. Your project and all diagrams will be restored

Generated by BESSER Web Modeling Editor
`;

    zip.file('README.md', readme);

    // Generate and download the ZIP file
    const content = await zip.generateAsync({ type: 'blob' });
    const filename = `${project.name.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'project'}_export.zip`;
    
    // Use our own download function instead of saveAs
    downloadBlob(content, filename);
    
  } catch (error) {
    console.error('ZIP export failed, falling back to JSON:', error);
    // Fallback to JSON export if ZIP fails
    await exportProjectAsJson(project, diagrams);
  }
}

export async function exportProjectById(project: BesserProject) {
  // Get all diagrams for this project from localStorage
  const diagrams = project.models
    .map(diagramId => {
      const diagramStr = localStorage.getItem(`besser_diagram_${diagramId}`);
      if (diagramStr) {
        try {
          return JSON.parse(diagramStr) as Diagram;
        } catch {
          return null;
        }
      }
      return null;
    })
    .filter(Boolean) as Diagram[];

  // Use ZIP export now that dependencies are available
  await useExportProjectJSON(project, diagrams);
}
